In [2]:
import pandas

jmena = pandas.read_csv(
    "https://kodim.cz/cms/assets/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani/excs/excs%3Estudenti/jmena.csv")
s1 = pandas.read_csv(
    "https://kodim.cz/cms/assets/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani/excs/excs%3Estudenti/studenti1.csv")
s2 = pandas.read_csv(
    "https://kodim.cz/cms/assets/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani/excs/excs%3Estudenti/studenti2.csv")

        jméno  četnost  věk pohlaví        svátek      původ
0        Jiří   296090   49       m          24.4      řecký
1         Jan   293938   40       m   24.6. a 6.7  hebrejský
2        Petr   272135   42       m  22.2. a 29.6      řecký
3        Jana   264944   50       ž          24.5  hebrejský
4       Marie   260526   65       ž          12.9  hebrejský
..        ...      ...  ...     ...           ...        ...
95   Jindřich    26230   51       m          15.7    německý
96  Vlastimil    26014   54       m          17.3  slovanský
97        Iva    26003   46       ž          1.12  slovanský
98      Miloš    25509   53       m          25.1  slovanský
99     Zdenka    25416   68       ž          23.6  slovanský

[100 rows x 6 columns]